app:
  security:
    oidc:
      enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:photo-gallery}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:change-me}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            authorization-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:photo-gallery}/protocol/openid-connect/auth"
            token-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:photo-gallery}/protocol/openid-connect/token"
            jwk-set-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:photo-gallery}/protocol/openid-connect/certs"
            user-info-uri: "${KEYCLOAK_BASE_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:photo-gallery}/protocol/openid-connect/userinfo"
            user-name-attribute: preferred_username
