server:
  port: 8090
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gallery_dev
    username: gallery
    password: gallery
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.default_schema: public

  flyway:
    enabled: true
    create-schemas: true
    default-schema: public
    schemas: public

  mvc:
    hiddenmethod:
      filter:
        enabled: true

photo:
  gallery:
    upload:
      dir: uploads
